apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-a
  namespace: pspd-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-a
  template:
    metadata:
      labels:
        app: grpc-a
    spec:
      containers:
      - name: grpc-a
        image: pspd/grpc-a:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        livenessProbe:
          tcpSocket: { port: 50051 }
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket: { port: 50051 }
          initialDelaySeconds: 2
          periodSeconds: 5
