apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-a
  namespace: pspd-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-a
  template:
    metadata:
      labels:
        app: grpc-a
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
      - name: grpc-a
        image: grpc-a:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          tcpSocket: { port: 50051 }
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket: { port: 50051 }
          initialDelaySeconds: 2
          periodSeconds: 5
