apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-b
  namespace: pspd-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-b
  template:
    metadata:
      labels:
        app: grpc-b
    spec:
      containers:
      - name: grpc-b
        image: grpc-b:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50052
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          tcpSocket: { port: 50052 }
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket: { port: 50052 }
          initialDelaySeconds: 2
          periodSeconds: 5
