apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-p
  namespace: pspd-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-p
  template:
    metadata:
      labels:
        app: grpc-p
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m03
      containers:
      - name: grpc-p
        image: grpc-p:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000  
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        env:
        - name: SERVER_A_HOST
          value: "grpc-a"
        - name: SERVER_A_PORT
          value: "50051"
        - name: SERVER_B_HOST
          value: "grpc-b"
        - name: SERVER_B_PORT
          value: "50052"
        livenessProbe:
          tcpSocket: { port: 3000 }
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket: { port: 3000 }
          initialDelaySeconds: 2
          periodSeconds: 5
