apiVersion: v1
kind: Service
metadata:
  name: grpc-p
  namespace: pspd-grpc
spec:
  type: NodePort
  selector:
    app: grpc-p
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
