version: "3.9"

services:
  a-service:
    build: ./A-py-rest
    container_name: a-service
    ports:
      - "6001:6001"
    networks:
      - rest-net

  b-service:
    build: ./B-py-rest
    container_name: b-service
    ports:
      - "6002:6002"
    networks:
      - rest-net

  p-gateway:
    build: ./P-nodejs-rest
    container_name: p-gateway
    ports:
      - "4000:4000"
    depends_on:
      - a-service
      - b-service
    environment:
      A_SERVICE_URL: http://a-service:6001
      B_SERVICE_URL: http://b-service:6002
    networks:
      - rest-net

networks:
  rest-net:
    driver: bridge
